/****** Skript für SelectTopNRows-Befehl aus SSMS ******/
SELECT
	--[AvailabilityId]
	[ZipCode]
	,[Quantity]
	,[TempAlloc]
	,[TempReserved]
	,[BBD]
	,[IsManual]
	,[TypeId]
	,[ClientId]
	,[Reliability]
	,[ReliabilityQuantity]
	,[ReliabilityQuality]
	,CONVERT(VARCHAR(33), [AvailableFromDate], 126) AS [AvailableFromDate]
	,CONVERT(VARCHAR(33), [AvailableUntilDate], 126) AS [AvailableUntilDate]
	,CONVERT(VARCHAR(33), [AvailableFromTime], 126) AS [AvailableFromTime]
	,CONVERT(VARCHAR(33), [AvailableUntilTime], 126) AS [AvailableUntilTime]
	,[ContactId]
	,[LoadingPointId]
	,[QualityId]
	,[AvailabilityTypeId]
	,[CommentText]
	,[CountryId]
	,[AvailabilitySubTypeId]
	,[PalletTypeId]
	,[ContactAddressInfo]
	,[ContractNo]
	,[DeliveryNoteNo]
	,[TransactionNo]
	,CONVERT(VARCHAR(33), [CreationDate], 126) AS [CreationDate]
	,NULL AS [ModificationDate]
	,[DeletionDate]
	,[CreatedBy]
	,NULL AS [ModifiedBy]
	,[DeletedBy]
	,[ContactPerson]
	,[ContactDetails]
	,[RepositoryHours]
	,[finished]
	,[IsMixedAvailability]
	,[LSManAdrAnrede]
	,[LSManAdrName1]
	,[LSManAdrName2]
	,[LSManAdrName3]
	,[LSManAdrPLZ]
	,[LSManAdrOrt]
	,[LSManAdrStrasse]
	,[LSManAdrLand]
	,[PalettenProMonat]
	,[PalettenProWoche]
	,[Notiz]
	--,[Geblockt]
	--,[GeblocktVon]
	--,[GeblocktDatum]
	--,[GeblocktAufgehobenVon]
	--,[GeblocktAufgehobenDatum]
	--,[GeblocktKommentar]
	--,[GeblocktFuer]
	--,[InBearbeitungVon]
	--,[InBearbeitungDatumZeit]
	,0 AS [Revision]
	--,[Storniert]
	--,[StorniertVon]
	--,[StorniertDatum]
	--,[StorniertKommentar]
	,[Rejection]
	,[Reklamation]
	,[RejectionReasonID]
	,[RejectionComment]
	,[RejectionQuantity]
	,[RejectionApproachID]
	,[RejectionBy]
	,[RejectionDate]
	,[RejectionDone]
	,[RejectionDoneComment]
	,[RejectionNextReceiptNo]
	,[RejectionDoneBy]
	,[RejectionDoneDate]
	,[RejectionCost]
	,[ICDroht]
	,[ICDrohtVon]
	,[ICDrohtAm]
	,[ICDurchfuehren]
	,[ICDurchfuehrenVon]
	,[ICDurchfuehrenAm]
	,[ZuAvisieren]
	,[IstAvisiert]
	,[AvisiertVon]
	,[AvisiertAm]
	,[IstAusAblehnung]
	,[IcGrundID]
	,[OrderManagementID]
	--,[RowGuid]
	--,[VersionCol]
	,[StackHeightMin]
	,[StackHeightMax]
	,[SupportsRearLoading]
	,[SupportsSideLoading]
	,[SupportsJumboVehicles]
	,[SupportsIndividual]
	,[BasePalletTypeId]
	,[BaseQualityId]
	,[ShowOnline]
	,[IsCreatedOnline]
	,1 AS [SupportsPartialMatching]
	,[IsHotspotOffer]
	,[HotspotComment]
	,CONVERT(VARCHAR(33), [HotspotOfferUntil], 126) AS [HotspotOfferUntil]
	,[OnlineComment]
	,[LiveDocumentNumber]
	,[ExpressCode]
	,[HasBasePallets]
	,[LoadingLocationId]
FROM [LMS].[dbo].[LMS_AVAILABILITY]
WHERE CONVERT(DATE, CreationDate) = '03.06.2020'
	AND CreatedBy = 'schmidt'
	AND Quantity > 1
ORDER BY [AvailabilityId] DESC
