import { Injectable } from '@angular/core';
import { PostingAccountApiService } from './backend-api.service';
import {
  PostingAccountsApiService,
  BalanceTransfersApiService,
  CountriesApiService,
  CustomersApiService,
  AccountingRecordsApiService,
  ExpressCodesApiService,
  DocumentsApiService,
  LoadCarriersApiService,
  LoadingLocationsApiService,
  OfferingsApiService,
  OrderMatchesApiService,
  OrdersApiService,
  PartnerDirectoriesApiService,
  PartnersApiService,
  UserApiService,
  UploadsApiService,
  VouchersApiService,
  DocumentSettingsApiService,
  MasterDataApiService,
  VouchersSummariesApiService,
  OrderGroupsApiService,
  PostingRequestsApiService,
  LoadCarrierReceiptsApiService,
  OrderLoadsApiService,
  DplEmployeeApiService,
  UserAdministrationApiService,
  UserGroupAdministrationApiService,
  OrganizationsAdministrationApiService,
  PermissionsAdministrationApiService,
  CustomerDivisionsAdministrationApiService,
  CustomersAdministrationApiService,
  PostingAccountsAdministrationApiService,
  AddressesAdministrationApiService,
  PartnersAdministrationApiService,
  LoadingLocationsAdministrationApiService,
  DivisionDocumentSettingsAdministrationApiService,
  NumberSequencesApiService,
  PostingAccountBalancesApiService,
  LoadCarrierSortingApiService,
} from './dpl-api-services';

@Injectable({
  providedIn: 'root',
})
export class DplApiService {
  constructor(
    public postingAccounts: PostingAccountsApiService,
    public balanceTransfer: BalanceTransfersApiService,
    public accountingRecords: AccountingRecordsApiService,
    public countries: CountriesApiService,
    public customers: CustomersApiService,
    public documents: DocumentsApiService,
    public documentSettings: DocumentSettingsApiService,
    public employeeService: DplEmployeeApiService,
    public expressCodes: ExpressCodesApiService,
    public loadCarriers: LoadCarriersApiService,
    public loadCarrierReceipts: LoadCarrierReceiptsApiService,
    public loadingLocations: LoadingLocationsApiService,
    public masterData: MasterDataApiService,
    public offerings: OfferingsApiService,
    public orderLoads: OrderLoadsApiService,
    public orderMatches: OrderMatchesApiService,
    public orders: OrdersApiService,
    public orderGroups: OrderGroupsApiService,
    public partnerDirectories: PartnerDirectoriesApiService,
    public partners: PartnersApiService,
    public postingRequests: PostingRequestsApiService,
    public uploads: UploadsApiService,
    public user: UserApiService,
    public vouchers: VouchersApiService,
    public voucherSummaries: VouchersSummariesApiService,
    public userAdmistrationService: UserAdministrationApiService,
    public numberSequencesApiService: NumberSequencesApiService,
    public groupAdministrationService: UserGroupAdministrationApiService,
    public permissionAdministrationService: PermissionsAdministrationApiService,
    public organizationsAdministrationService: OrganizationsAdministrationApiService,
    public customersAdministrationService: CustomersAdministrationApiService,
    public divisionsAdministrationService: CustomerDivisionsAdministrationApiService,
    public postingAccountsAdministrationService: PostingAccountsAdministrationApiService,
    public addressesAdministrationService: AddressesAdministrationApiService,
    public partnersAdministrationService: PartnersAdministrationApiService,
    public divisionDocumentSettingsAdministrationApiService: DivisionDocumentSettingsAdministrationApiService,
    public loadingLocationsAdministrationService: LoadingLocationsAdministrationApiService,
    public postingAccountBalancesApiService: PostingAccountBalancesApiService,
    public loadCarrierSortingService: LoadCarrierSortingApiService
  ) {}
}
