using System;
using System.Collections.Generic;

namespace Dpl.B2b.Dal.Models.Lms
{
    public partial class LmsViewAvailability
    {
        public int AvailabilityId { get; set; }
        public string ZipCode { get; set; }
        public int Quantity { get; set; }
        public bool? TempAlloc { get; set; }
        public bool? TempReserved { get; set; }
        public DateTime? Bbd { get; set; }
        public bool IsManual { get; set; }
        public int TypeId { get; set; }
        public int ClientId { get; set; }
        public int? Reliability { get; set; }
        public int? ReliabilityQuantity { get; set; }
        public int? ReliabilityQuality { get; set; }
        public DateTime? AvailableFromDate { get; set; }
        public DateTime? AvailableUntilDate { get; set; }
        public DateTime? AvailableFromTime { get; set; }
        public DateTime? AvailableUntilTime { get; set; }
        public int? ContactId { get; set; }
        public int? LoadingPointId { get; set; }
        public int? QualityId { get; set; }
        public int? AvailabilityTypeId { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? ModificationDate { get; set; }
        public DateTime? DeletionDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string DeletedBy { get; set; }
        public string CommentText { get; set; }
        public int? CountryId { get; set; }
        public int? AvailabilitySubTypeId { get; set; }
        public int? PalletTypeId { get; set; }
        public string ContactAddressInfo { get; set; }
        public string ContractNo { get; set; }
        public string DeliveryNoteNo { get; set; }
        public string TransactionNo { get; set; }
        public string RepositoryHours { get; set; }
        public string ContactDetails { get; set; }
        public string ContactPerson { get; set; }
        public bool Finished { get; set; }
        public bool IsMixedAvailability { get; set; }
        public string LsmanAdrAnrede { get; set; }
        public string LsmanAdrName1 { get; set; }
        public string LsmanAdrName2 { get; set; }
        public string LsmanAdrName3 { get; set; }
        public string LsmanAdrPlz { get; set; }
        public string LsmanAdrOrt { get; set; }
        public string LsmanAdrStrasse { get; set; }
        public string LsmanAdrLand { get; set; }
        public int PalettenProMonat { get; set; }
        public int PalettenProWoche { get; set; }
        public string Notiz { get; set; }
        public bool? Geblockt { get; set; }
        public string GeblocktVon { get; set; }
        public DateTime? GeblocktDatum { get; set; }
        public string GeblocktAufgehobenVon { get; set; }
        public DateTime? GeblocktAufgehobenDatum { get; set; }
        public string GeblocktKommentar { get; set; }
        public string GeblocktFuer { get; set; }
        public string InBearbeitungVon { get; set; }
        public DateTime? InBearbeitungDatumZeit { get; set; }
        public int? Revision { get; set; }
        public bool? Rejection { get; set; }
        public int? RejectionReasonId { get; set; }
        public int? RejectionQuantity { get; set; }
        public int? RejectionApproachId { get; set; }
        public string RejectionComment { get; set; }
        public string RejectionBy { get; set; }
        public DateTime? RejectionDate { get; set; }
        public bool? RejectionDone { get; set; }
        public string RejectionDoneComment { get; set; }
        public string RejectionNextReceiptNo { get; set; }
        public string RejectionDoneBy { get; set; }
        public DateTime? RejectionDoneDate { get; set; }
        public bool? Storniert { get; set; }
        public string StorniertVon { get; set; }
        public DateTime? StorniertDatum { get; set; }
        public string StorniertKommentar { get; set; }
        public bool? IstAusAblehnung { get; set; }
        public double? RejectionCost { get; set; }
        public bool? Icdroht { get; set; }
        public string IcdrohtVon { get; set; }
        public DateTime? IcdrohtAm { get; set; }
        public bool? Icdurchfuehren { get; set; }
        public string IcdurchfuehrenVon { get; set; }
        public DateTime? IcdurchfuehrenAm { get; set; }
        public bool? ZuAvisieren { get; set; }
        public bool? IstAvisiert { get; set; }
        public string AvisiertVon { get; set; }
        public DateTime? AvisiertAm { get; set; }
        public bool? Reklamation { get; set; }
        public string OrderManagementId { get; set; }
    }
}
